CXX = g++-10
CXXFLAGS = -g -Wall -Wextra -Werror -Wpedantic -std=c++17

step0_repl: step0_repl.cpp
	$(CXX) $(CXXFLAGS) -o step0_repl step0_repl.cpp
clean:
	rm -f step0_repl
	rm -f *~ *.o
	rm -rf *.dSYM